# To use:
#   $ conda env create -f environment.yaml  # `mamba` works too for this command
#   $ conda activate cherab-lhd-dev
#
name: cherab-lhd-dev
channels:
- conda-forge
- default
dependencies:
- python >= 3.10
- meson >= 0.64.0
- meson-python >= 0.10.0
- ninja >= 1.8.2
# - cython >= 3.0.0 installed by pip temporarily
- numpy
- scipy
- matplotlib
- plotly
- h5py
  # for developper tools
- ipython
- black
- ruff
- mypy
- rich-click
- pre-commit
- pycodestyle  # dependency for cython-lint
  # for documentation
- docutils >= 0.19, < 0.20
- ipykernel
- ipywidgets
- nbsphinx
- pillow
- pygments >= 2.11.0
- sphinx >= 5, < 6
- sphinx-prompt
- sphinx-copybutton
- pydata-sphinx-theme < 0.11
- sphinx-design
- pandoc < 3.0
- sphinx-codeautolink
# pip-install dependencies
- pip
- pip:
  - cython == 3.0.0b3
  - raysect @ git+https://github.com/munechika-koyo/source.git@feature/tetrahedra_mesh
  - cherab @ git+https://github.com/munechika-koyo/core.git@raysect-0.8-compat
  - cython-lint
