# To use:
#   $ conda env create -f environment.yaml  # `mamba` works too for this command
#   $ conda activate cherab-lhd-dev
#
name: cherab-lhd-dev
channels:
- conda-forge
dependencies:
- python >= 3.10
- meson-python >= 0.13.0
- cython >= 3.0
- numpy
- scipy
- matplotlib
- plotly
- h5py
  # for developper tools
- tomli  # for python < 3.11
- black
- ruff
- mypy
- rich-click
- pre-commit
- cython-lint
- pytest
  # for documentation
- docutils
- ipykernel
- ipywidgets
- nbconvert > 7.3
- nbsphinx
- pillow
- pygments >= 2.11.0
- sphinx
- sphinx-prompt
- sphinx-copybutton
- pydata-sphinx-theme < 0.15  # for custom css dependency
- sphinx-design
- pandoc
- sphinx-codeautolink
# pip-install dependencies
- pip
- pip:
  - sphinx-github-style
  - raysect @ git+https://github.com/munechika-koyo/source.git@feature/tetrahedra_mesh
  - cherab @ git+https://github.com/munechika-koyo/core.git@raysect-0.8-compat
