[build-system]
requires = [
    "setuptools >= 40.9.0",
    "wheel",
    "numpy",
    "cython",
    "raysect @ git+https://github.com/munechika-koyo/source.git@feature/tetrahedra_mesh",
    "cherab @ git+https://github.com/cherab/core.git@raysect-0.8-compat",
]
build-backend = "setuptools.build_meta"


# for development
[tool.flake8]
max-line-length = 100
select = "C,E,F,W,B,B950"
ignore = "E203,E501"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
ollow-imports = "silent"
ignore-missing-imports = true
show-column-numbers = true
no-pretty = true
